function p = singlegaupdf(model, x, y)
% Compute p(x|y) for specific y
    p = ( 1 / (                                                         ...
                (2 * pi)^(3 / 2) * det(model.cov(:,:,y))^(1/2) ...
              )                                                         ...
        )                                                               ...
        *                                                               ...
        (                                                               ...
              exp(                                                      ...
                    (-1/2)                  ...
                    * (x - model.mu(y,:))   ...
                    * inv(model.cov(:,:,y)) ...
                    * (x - model.mu(y,:))'  ...
                 )                                                      ...
        );

end
